[workspace]
members = [
    "nbt-test",
    # "shen-nbt1",  # EOL!
    # "shen-nbt2",
    # "shen-nbt3",
    # "shen-nbt4",
    "shen-nbt5",
    "trait-test",
]
resolver = "2"

[profile.release]
debug = true
